### ISSUE TITLE
Not available

### ISSUE THREAD

**Issue by uqsme** [SunsetMkt/b23.tv-tools#2]
```plain
https://game.bilibili.com/linkfilter/?url=https://www.huawei.com/cn/corporate-information
```

**Comment by SunsetMkt** [comment]
URL determination is done on Bilibili's server, not an issue with this project.

It appears that they have banned any URL with a non-empty `url` argument.

**Comment by uqsme** [comment]
> It appears that they have banned any URL with a non-empty url argument.

```
https://passport.bilibili.com/login?gourl=https%3A%2F%2Fwww.bilibili.com%2Fblackboard%2Fera%2F3ERAmwloghvoqs00.html
```
可以被正常转换成 `https://b23.tv/UJCGr7I` ，从该短链接登陆后也可以来到对应的活动页，又做逆转换，得到的是 `gourl=` 参数之后的结果（当然是原链接而不是urlencode过的）。

如果试图把 `gourl` 参数换成非B站域名的话，则转成了 `https://passport.bilibili.com/login` 。

不是杠，仅作一个记录，如果未来有人看到这里的话

**Comment by TheInterestingS0ul** [comment]
欢迎查看我(SkymontVibe)的个人主页 @RewindBird 捏 😋
我就是超级节奏王，造假王，喜欢到处在别人的地盘上拉屎的Tis有趣的灵魂捏 🤣👉🤡
